[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zesus-example-fs"
version = "0.1.0"
dependencies = ["zesus"]

[project.entry-points."zesus.filesystems"]
examplefs = "zesus_example:ExampleFsPlugin"

[tool.hatch.build.targets.wheel]
packages = ["src/zesus_example"]
